### ISSUE TITLE
How to return Copyright in Chinese?

### ISSUE THREAD

**Issue by link9596** [grubersjoe/bing-daily-photo#10]
I visited `https://cn.bing.com/HPImageArchive.aspx?Format=js&idx=0&n=1&nc=1564281480718&pid=hp` with a browser and returned Chinese.

But I put it on the server ,it return in English.

How to customize the language it returns?

**Comment by grubersjoe** [comment]
Bing's API has a market parameter called `mkt`. You can set the desired locale code there like this (`&mkt=zh-cn`):

https://cn.bing.com/HPImageArchive.aspx?Format=js&idx=0&n=1&nc=1564281480718&pid=hp&mkt=zh-cn

If you're using this library, you can specify the locale in the following manner:

```php
$bing = new grubersjoe\BingPhoto([
    'locale' => 'zh-cn',
]);

var_dump($bing->getImage());
```

Does this help?

**Comment by link9596** [comment]
I found out the reason. It returns different content according to your IP address. In China, it is divided into two kinds. One is the international version and the other is the Chinese version. Sometimes they return different content.

So, I just need to disguise my request IP address:

```php
<?php

$hdrs = array(
         'http' =>array('header' =>
                    "Accept: application/json\r\n" .
                    "X-FORWARDED-FOR: 123.125.71.38\r\n" .
                    "Accept-Language: zh-cn,zh;q=0.8,en-us;q=0.5,en;q=0.3\r\n" ,
                    'timeout'=>2
         ),

);
$context = stream_context_create($hdrs);

    $str=file_get_contents('https://cn.bing.com/HPImageArchive.aspx?idx=0&n=1',0, $context);
?>
```

My problem has been solved.

**I am very grateful for your replay!**:smile:

**Wish you have a nice day! thank you!**:+1:

**Comment by grubersjoe** [comment]
Good to hear, that you got it working. Have a nice day too :sunflower:!
