### ISSUE TITLE
Access to details..

### ISSUE THREAD

**Issue by emresaracoglu** [grubersjoe/bing-daily-photo#11]
Hello,

I've been using your project for two years. Thank you so much. Also works great with caching! 🥇  #2  :)

Can you get the name of the photo, the name of the photographer, and other information?

For example;

![Screenshot_2019-12-26 Bing](https://user-images.githubusercontent.com/297968/71451320-7411b680-277b-11ea-8061-cdd4004b1adf.png)

**Comment by grubersjoe** [comment]
Hey,

nice to hear that you like it!

The description and copyright notice can be found in the **copyright** entry of the fetched array. Example of today:

```
Array
(
    // ...
    [url] => https://www.bing.com/th?id=OHR.SloveniaAlps_EN-US3700970842_1920x1080.jpg&rf=LaDigue_1920x1080.jpg&pid=hp
    [urlbase] => /th?id=OHR.SloveniaAlps_EN-US3700970842
    [copyright] => The Church of St. Thomas above the village of Praprotno, for Slovenia Independence and Unity Day (© Guy Edwardes/Minden Pictures)
    [copyrightlink] => https://www.bing.com/search?q=Slovenia+Independence+and+Unity+Day&form=hpcapt&filters=HpDate%3a%2220191226_0800%22
    [title] => It's Slovenia's Independence and Unity Day
    // ...
)
```

Does this help?

**Comment by emresaracoglu** [comment]
You have written before in the `Readme.md` file but I didn't notice yesterday. Sorry 
**Thank you for your time.**
