### ISSUE TITLE
Dimensions interchanged

### ISSUE THREAD

**Issue by wintstar** [grubersjoe/bing-daily-photo#14]
https://github.com/grubersjoe/bing-daily-photo/blob/8164ab631abc57627efea78be321c4e7241b4830/src/BingPhoto.php#L20

Dimensions interchanged. Correct is:

`public const QUALITY_LOW = '768x1366'; `

**Comment by grubersjoe** [comment]
Hey. Not sure if I understand. If you switch the x and y values you will receive the image in the respective ratio:

16:9 (landscape, currently used)
https://www.bing.com/th?id=OHR.ChukchiSea_DE-DE3561645051_1366x768.jpg&rf=LaDigue_1366x768.jpg&pid=hp

9:16 (portrait)
https://www.bing.com/th?id=OHR.ChukchiSea_DE-DE3561645051_768x1366.jpg&rf=LaDigue_1366x768.jpg&pid=hp

The purpose of this library is to provide the landscape version of the images. So why should I switch the values?

It might be nice to have an option to fetch landscape or portrait version in the future, though.

**Comment by wintstar** [comment]
Ok. Good idea with the option to change. I have changed it for me. Look here https://sf-atelier.stephan-frank.de/

**Comment by grubersjoe** [comment]
Ah, so you simply want portrait orientation, got it. I've added an option for that in v4.1.

```php
$bing = new BingPhoto([
    'orientation' => BingPhoto::ORIENTATION_PORTRAIT
]);
```
