### ISSUE TITLE
Cache

### ISSUE THREAD

**Issue by emresaracoglu** [grubersjoe/bing-daily-photo#2]
Hello,

Cache for only one day, it's possible?

Thanks

**Comment by grubersjoe** [comment]
Hey,

if I understand you correctly you want a feature, that saves the current image of the day to a local file, so that during a 24 hour period of time no further API requests for this image are necessary? Is this correct?

I like the idea and this should be easy to implement. I'll look into it!

**Comment by emresaracoglu** [comment]
Hi again,

Any changes? :)

**Comment by grubersjoe** [comment]
Sorry for the late response. I finally found time to work on this: See the [`caching`](https://github.com/grubersjoe/bing-daily-photo/tree/caching) branch. A few small details are missing, but not much. I'm going to finish this in the next days. Feel free to test it ;).

**Comment by grubersjoe** [comment]
@emresaracoglu This feature is available now.

**Comment by emresaracoglu** [comment]
I must have overlooked your first message. **I'm sorry** about that.
**Thank you for your work.**
cc @grubersjoe
