### ISSUE TITLE
locale(mkt) param not worked as expected

### ISSUE THREAD

**Issue by yueim** [grubersjoe/bing-daily-photo#7]
Seems that is not the issue of your code and the locale(mkt) param is determined by bing.com server (maybe detect the geo ip). And I'm located in Chine mainland.

See the difference below:
![WX20190406-125753](https://user-images.githubusercontent.com/275233/55665126-4ba00000-586c-11e9-9ecd-f0f33e098970.png)
![WX20190406-125600](https://user-images.githubusercontent.com/275233/55665128-4c389680-586c-11e9-8ede-a2854df9bce6.png)

**Comment by yueim** [comment]
a discussion on microsoft.com:
https://social.msdn.microsoft.com/Forums/en-US/77c44bca-190a-44f7-90e7-1ee0114b9e77/problem-with-httpwwwbingcomhpimagearchiveaspxformatxmlampidx0ampn1ampmktenus?forum=DataMarket

and another report on github.com
https://github.com/neffo/bing-wallpaper-gnome-extension/issues/20

**Comment by yueim** [comment]
get this done with add ```&mbl=1``` before ```&mkt=```, it's worked as expected. I'll pr this update later.

**Comment by yueim** [comment]
So sad and so sorry, ```mbl=1``` can not fix it.

**Comment by grubersjoe** [comment]
Sorry for the late reply. So if this not an issue with my code, I fear there's nothing I can do. Closing this for now... Feel free to reopen this, if there's a way to handle this.
