### ISSUE TITLE
FYI: this is not Meteora in Greece

### ISSUE THREAD

**Issue by pakair** [grubersjoe/bing-daily-photo#9]
http://www.bing.com/az/hprichbg/rb/Meteora_EN-US6763889417_1920x1080.jpg

This is not Meteora in Greece ...

**Comment by grubersjoe** [comment]
Sorry but this library simply reflects whatever the Bing API returns. There's no way to control the output...

The API is available at this endpoint:
https://www.bing.com/HPImageArchive.aspx?format=js&idx=0&n=1&mkt=en-US
